"""add more settings

Revision ID: aba718942a0c
Revises: fd5d6ce668fe
Create Date: 2024-05-16 08:51:53.623132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba718942a0c'
down_revision = 'fd5d6ce668fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_level'))
    )
    op.create_table('users_settings_level',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('settings_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['settings_level_id'], ['settings_level.id'], name=op.f('fk_users_settings_level_settings_level_id_settings_level')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_users_settings_level_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'settings_level_id', name=op.f('pk_users_settings_level'))
    )
    with op.batch_alter_table('users_collectable_items', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('collectable_items_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_collectable_items', schema=None) as batch_op:
        batch_op.alter_column('collectable_items_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timestamp')

    op.drop_table('users_settings_level')
    op.drop_table('settings_level')
    # ### end Alembic commands ###
