"""colors for coloctable items

Revision ID: ba597766da73
Revises: 697392627508
Create Date: 2024-05-19 07:08:34.269631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba597766da73'
down_revision = '697392627508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectable_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectable_items', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
