"""change in user

Revision ID: fceb6960a9eb
Revises: c1c924af060c
Create Date: 2024-05-16 23:36:08.397123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fceb6960a9eb'
down_revision = 'c1c924af060c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_settings_level_id_settings_level'), 'settings_level', ['settings_level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_settings_level_id_settings_level'), type_='foreignkey')
        batch_op.drop_column('settings_level_id')

    # ### end Alembic commands ###
