"""add operator to settings_operators

Revision ID: fd5d6ce668fe
Revises: f199f1d785e3
Create Date: 2024-05-15 22:33:37.347988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5d6ce668fe'
down_revision = 'f199f1d785e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_operators', schema=None) as batch_op:
        batch_op.drop_column('operator')

    # ### end Alembic commands ###
